---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: ../
  playbook: playbook.yml
  hosts: localhost
  require_ansible_repo: true
  ansible_verbose: true
  # ansible_version: 1.8.2
  ansible_yum_repo: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm

platforms:
  - name: opscode-centos71
    driver_plugin: vagrant
    driver_config:
      box: opscode-centos-7.1
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box

suites:
  - name: default
    run_list:
    attributes:
